Metrics/AbcSize:
  Enabled: false
  
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false  

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/AlignHash:
  EnforcedColonStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
